### ISSUE TITLE
Question: Is the music heard by all those around in game?

### ISSUE THREAD

**Issue by TheDevster** [kibook/redm-instruments#1]
Have not tested it, but am playing with it on my solo server. Wondering if others were around if they'd be able to hear.

**Comment by kibook** [comment]
Yes, they can. It works basically the same as the [phonograph resource](https://github.com/kibook/redm-phonograph), so the volume is based on distance from another player and whether you're in the same interior room as them.

If you're on the same channel, you'll also see what notes another player is playing on the piano keyboard.

**Comment by TheDevster** [comment]
That is awesome!  Thanks for the resource and the answer.
